import ContactSection from "@/components/ContactSection/ContactSection";
import Features from "@/components/Features/Features";
import Hero from "@/components/Hero/Hero";
import Layouts from "@/components/Layouts/Layouts";
import Projects from "@/components/Projects/Projects";
import Info from "@/components/Info/Info";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layouts>
        <Hero />
        <Info />
        <Features />
        <Projects />
        <ContactSection />
      </Layouts>
    </>
  );
}
